# Generated by Django 4.2.11 on 2026-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("rated_user", "rating_user"), name="unique_rating_per_user_pair"
            ),
        ),
    ]
