# Generated by Django 4.2.11 on 2025-03-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="object_id",
            field=models.BigIntegerField(verbose_name="Object ID"),
        ),
    ]
