# Generated by Django 4.2.11 on 2025-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_contentview_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="object_id",
            field=models.CharField(max_length=36, verbose_name="Object ID"),
        ),
    ]
