# Generated by Django 4.2.11 on 2025-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_contentview_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="object_id",
            field=models.BigIntegerField(verbose_name="Object ID"),
        ),
    ]
