# Generated by Django 4.2.11 on 2026-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_contentview_object_id"),
    ]

    operations = [
       # 1. Drop the old integer column
        migrations.RemoveField(
            model_name='contentview',
            name='object_id',
        ),
        # 2. Add it back as UUIDField
        migrations.AddField(
            model_name='contentview',
            name='object_id',
            field=models.UUIDField(default=None, null=True),
            preserve_default=False,
        ),
    ]
