# Generated by Django 4.2.11 on 2026-10-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_contentview_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="object_id",
            field=models.UUIDField(),
        ),
    ]
