# Generated by Django 4.2.11 on 2026-10-02 13:22

import core_apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[core_apps.users.models.UsernameValidator()],
                verbose_name="Username",
            ),
        ),
    ]
