# Generated by Django 4.2.11 on 2025-03-09 21:38

import autoslug.fields
import cloudinary.models
import core_apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Avatar"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "female")],
                        default="male",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("mason", "Mason"),
                            ("plumber", "Plumber"),
                            ("painter", "Painter"),
                            ("roofer", "Roofer"),
                            ("electrician", "Electrician"),
                            ("carpenter", "Carpenter"),
                            ("hvac", "Hvac"),
                            ("tenant", "Tenant"),
                        ],
                        default="tenant",
                        max_length=20,
                        verbose_name="Occupation",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+353877800112",
                        max_length=13,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "country_field",
                    django_countries.fields.CountryField(
                        default="IE", max_length=2, verbose_name="Country Field"
                    ),
                ),
                (
                    "city_of_origin",
                    models.CharField(
                        default="Dublin", max_length=100, verbose_name="City Of Origin"
                    ),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="Report Count"),
                ),
                (
                    "reputation",
                    models.IntegerField(default=100, verbose_name="Reputation"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core_apps.profiles.models.get_user_username,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
